name: Angular CI

on:
  push:
    branches: [ master, feature ]
  pull_request:
    branches: [ master, feature ]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Angular with npm
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Build Angular with npm
    - run: | 
        npm ci
        npm run build --if-present
        npm run build-prod --if-present
        npm test
